apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-slack-auth-token-secret
type: Opaque
data:
  slack-auth-token: {{ .Values.cronJob.slackAuthToken | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-slack-webhook-url-secret
type: Opaque
data:
  slack-webhook-url: {{ .Values.cronJob.slackWebhookUrl | b64enc | quote }}
